<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mgt"
    nsURI="http://mgt/1.0" nsPrefix="mgt">
  <eClassifiers xsi:type="ecore:EClass" name="TestSuite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemUnderTest" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCases" lowerBound="1"
        upperBound="-1" eType="#//TestCase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSteps" lowerBound="1"
        upperBound="-1" eType="#//AbstractTestStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verdict" lowerBound="1"
        eType="#//Verdict"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTestStep" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestDate" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//TestDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//TestDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//TestDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//AbstractTestStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assert" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verdict" eType="#//Verdict"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expected" eType="#//TestDate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actual" lowerBound="1"
        eType="#//Keyword" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Verdict">
    <eLiterals name="fail"/>
    <eLiterals name="pass" value="1"/>
    <eLiterals name="inconclusive" value="2"/>
    <eLiterals name="error" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Keyword" eSuperTypes="#//AbstractTestStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//UIElementLocator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testData" upperBound="-1"
        eType="#//TestDate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIElementLocator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//AbstractTestStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialStep" eSuperTypes="#//AbstractTestStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" lowerBound="1"
        eType="#//Sequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//TestDate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
